---
- name: Update iLO Firmware
  command: "hpilo_cli {{ item.host }} --json --login={{ item.login }} --password={{ item.password }} update_rib_firmware version={{ ilo_firmware_version }}"
  register: hpilo_cli_update_firmware
  delegate_to: localhost
  loop: "{{ ilo_hosts }}"
